# action.yml
name: 'Slicer Build'
description: 'Build Slicer using BuildSlicer.sh script provided by the slicer/slicer-base docker image'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
