branches:
 only:
  - master
  - /^v[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/

language: python

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.0

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; ln -s $(which python2) $HOME/bin/python; fi
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U scikit-ci scikit-ci-addons
  - ci_addons --install ../addons

install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test

deploy:
  - provider: script
    script: pwd && ls dist;echo "deploy-release" && ~/.pyenv/versions/${PYTHON_VERSION}/bin/twine upload -u $PYPI_USER -p $PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      tags: true
  - provider: script
    script: pwd && ls dist && echo "deployment-nightly"
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master

notifications:
  email: false

env:
  global:
    # PYPI_USER
    - secure: "J1YOYfqNC3e2g2KJxQb4zK4iBSERuSPS+VBHnBuDbxy+9UbeiVUF4NWwYYjThSA5zsS5Eb6vUWE5lOdWZ2qNydQ/Ef8rfCH/DnMEISeNOuDG7wNyX5u3ZW+usZC6MRdJM3ONnXzPB37ogLoEnVODDY+OodF9sFSA/h45+04skSLfNmUyU/lFg5SdKWMopzUCtFsWJToGcwEwghYOB48uFPELM2klUkMIH726V8AH32x1a//TAqs+5Nv8AiX7d6J/XAdmvzyEm58jtmzcX2ARcXSIAd76mqL2iXi5CJsBl2S8AWPenSVHciBGB2GVJ30l55Hf0YlgXO/QfG1dDSuTOqFwrD1ZvsGZBqICHZNVBejZWemoG60EjCqUk1UNUASz19AWuPz7OyBTYWg2tUjEttFhEtO/EmHB6CuUj+N7SxuZm39ATDsj6ohKHJxwjABuNSijmSEdhO8WAGWVfL/VLVtDej99BClY+cMYYLYf6RLxt1+psYStHZFglsWZ4Hcxf3pVPfT4RXJt4H83H0HsXeB2/MqOTbQ0HFGHdZ9hhXrrmse7YoGHteaDUPQi/22i+eXZXDFsPksUtjaluP6hzcjA42ki4iok3Zjtzx8xtbKkqm/Q7BG06AVEsg71LqZ0nIpvi892E6VeAgG73BufpZbgLARIwjku4la52Jdl4hI="

    # PYPI_PASSWORD
    - secure: "ij7OIOrrPtB+A4lEyoe0kEGmStaFV5mSdb7o9yTQ990gjrihs47miYn8anvM4op6dz4/AyzVORDcvKb+te4MOQ1jsYiGQlpxEcR87nbrlcI3x3zG605Bn2nTE+EE9fOCE64jqtboL+b7V4agymlCcSMVRUPMiIJFuGQk+EvMRLAsaKdC9lThEHRmoIlmmTpDDcL1GxQlu/9ebQb9BgxIY7lCw7irQX5+jIYMxqmvxgNVmjeppfa5G7PVJKAcD0zTJfqsQCsTziONOV/uvKlzlcISUQrFVpH/X9LfoIfJBRa7ACLzwnlORlgzaa4uWmm1zSGXKHnb0MPVP9VN74QAdt9Ju90+TZ2AH63JwRAHyFJeEcZ5kacXhPvP3wLU5U/n2qV8/gq2/p2afRFYimPiUhIhm6jUBQsHQDVWtcUFXj4h4HIy3FccDqDvK7tI6qkB5LtRisXcrWsDcqwgZ5vmnXEHLAAks2BqIpeqvvRT1adBt5flzst21+HLdhO6pkFXgCC7yJ30H4yndSE3qDVOaxmTLINuRn3yWxdk6S16Fsx/jsO0AbPIUAqL+KYJR3w2Mpe+WxpUeCjDjEtSnhEre3z1S5iKxSffAY7jPkQ7zSPY+Lxi76wv0i3je+RdJTrpgFBpH++Ql93/lmObDQj3LcfytdOk+81LTgAEdaQmb6w="
