branches:
 only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: python

before_install:
  - echo "before_install"

install:
  - echo "install"

script:
  - echo "script"

after_success:
  - echo "success"

deploy:
  - provider: script
    script: pwd && ls && cd /home/travis/build/jcfr/ci-sandbox && echo "deployment-release"
    skip_cleanup: true
    on:
      repo: jcfr/ci-sandbox
      tags: true
  - provider: script
    script: pwd && ls && cd /home/travis/build/jcfr/ci-sandbox && echo "deployment-nightly"
    skip_cleanup: true
    on:
      repo: jcfr/ci-sandbox
      branch: master

notifications:
  email: false
