branches:
 only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: python
python:
  - "3.6"

before_install:
  - echo "before_install"
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U setuptools twine wheel

install:
  - echo "install"

script:
  - echo "script"
  - python setup.py sdist bdist_wheel

after_success:
  - echo "success"

deploy:
  - provider: script
    script: pwd && ls && cd /home/travis/build/jcfr/ci-sandbox && echo "deployment-release"
    skip_cleanup: true
    on:
      repo: jcfr/ci-sandbox
      tags: true
  - provider: script
    script: pwd && ls && cd /home/travis/build/jcfr/ci-sandbox && echo "deployment-nightly"
    skip_cleanup: true
    on:
      repo: jcfr/ci-sandbox
      branch: master

notifications:
  email: false
