branches:
 only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/



language: cpp
env:
- PYENV_VERSION='2.7.15' PYENV_VERSION_STRING='Python 2.7.15'

cache:
  - directories:
    - "$HOME/.pyenv_cache"

before_install:
  - echo "before_install"
  - |
    cd /opt/pyenv && git pull origin master && cd -
    export PATH=/opt/pyenv/versions/${PYENV_VERSION}/bin:${PATH}
    pyenv install ${PYENV_VERSION}
    ls /opt/pyenv/versions/${PYENV_VERSION}/bin
  - pyenv global ${PYENV_VERSION}
install:
  - echo "install"

script:
  - echo "script"
  - python -c "import platform; print(platform.system().lower())"

after_success:
  - echo "success"

deploy:
  - provider: script
    script: pwd && ls && cd /home/travis/build/jcfr/ci-sandbox && echo "deployment-release"
    skip_cleanup: true
    on:
      repo: jcfr/ci-sandbox
      tags: true
  - provider: script
    script: pwd && ls && cd /home/travis/build/jcfr/ci-sandbox && echo "deployment-nightly"
    skip_cleanup: true
    on:
      repo: jcfr/ci-sandbox
      branch: master

notifications:
  email: false
