branches:
  only:
    - master
    - /^v[0-9]+(\.[0-9]+)*/

version: "0.0.1.{build}"

environment:
  PYTHON_DIR: "C:\\Python36-x64"
  PATH: "%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"
  BLOCK: "0"
  PYPI_USER:
    secure: UGVCrlMzqZYEKC4ukxwT9g==
  PYPI_PASSWORD:
    secure: meCzpEOhlwp5AZazjODrkVU+u9xn4uvGKGfwEMsncqM=

init:
  - echo "init"

install:
  - echo "install"
  - echo "PATH:%PATH%"
  - echo "PYTHON_DIR:%PYTHON_DIR%"
  - python --version
  - dir %PYTHON_DIR%
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U setuptools twine wheel
  - pip install -U scikit-ci-addons
  - ci_addons --install ../addons

build_script:
  - echo "build_script"
  - python setup.py sdist bdist_wheel
  - ps: |
      #
      # if it applies, remove source distribution
      #
      if (!$env:UPLOAD_SDIST) {
        Write-Host "Deleting source distribution"
        Remove-Item –path dist/*.tar.gz
      }

test_script:
  - echo "test_script"

after_test:
  - echo "after_test"

on_finish:
  - echo "on_finish"
  - ps: ../addons/appveyor/enable-worker-remote-access.ps1 -check_for_block

deploy_script:
  - ps: |
      if ($env:appveyor_repo_tag -eq $true -and $env:appveyor_repo_tag_name –match "^v[0-9]+(\.[0-9]+)*") {
        Write-Host "deploy release"
        pip install twine
        twine upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ dist/*
      } elseif ($env:appveyor_repo_branch -eq "master") {
         Write-Host "deploy master"
         dir dist
      } else {
        Write-Host "deploy nothing"
      }

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

matrix:
  fast_finish: false

shallow_clone: false


notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

