version: "0.0.1.{build}"

init:
  - echo "init"

install:
  - echo "install"

build_script:
  - echo "build_script"

test_script:
  - echo "test_script"

after_test:
  - echo "after_test"

on_finish:
  - echo "on_finish"

deploy_script:
  - ps: |
      if ($env:appveyor_repo_tag -eq $true -and $env:appveyor_repo_tag_name –match "^v[0-9]+(\.[0-9]+)*") {
        Write-Host "deploy release"
      } elseif ($env:appveyor_repo_branch -eq "master") {
         Write-Host "deploy master"
      } else {
        Write-Host "deploy nothing"
      }

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

matrix:
  fast_finish: false

shallow_clone: false


notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

