branches:
  only:
    - master
    - /^v[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/

version: "0.0.1.{build}"


environment:
  matrix:

    - PYTHON_DIR: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

  PYPI_USER:
    secure: UGVCrlMzqZYEKC4ukxwT9g==
  PYPI_PASSWORD:
    secure: meCzpEOhlwp5AZazjODrkVU+u9xn4uvGKGfwEMsncqM=

init:
  - python -m pip install -U scikit-ci scikit-ci-addons
  - python -m ci_addons --install ../addons

install:
  - python -m ci install

build_script:
  - python -m ci build

test_script:
  - python -m ci test

after_test:
  - python -m ci after_test

on_finish:
  - ps: ../addons/appveyor/enable-worker-remote-access.ps1 -check_for_block


deploy_script:
  - ps: |
      if ($env:appveyor_repo_tag -eq $true -and $env:appveyor_repo_tag_name –match "^v[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$") {
        Write-Host "deploy release"
        $env:PYTHON_DIR + '/Scripts/twine' upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
      } elseif ($env:appveyor_repo_branch -eq "master") {
         Write-Host "deploy master"
         dir dist
      } else {
        Write-Host "deploy nothing"
      }

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

matrix:
  fast_finish: false

shallow_clone: false


notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

