trigger:
  - master

jobs:
  - job: Windows

    pool:
      vmImage: 'vs2017-win2016'

    steps:

      - powershell: |
          $environmentVars = get-childitem -path env:*
          foreach($var in $environmentVars)
          {
           $keyname = $var.Key
           $keyvalue = $var.Value

           Write-Output "${keyname}: $keyvalue"
          }
        displayName: Display env. variables

      - powershell: |
          $pythonArch = "64"
          iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/scikit-build/scikit-ci-addons/master/windows/install-python.ps1'))
        displayName: Test install-python.ps1

