
references:

  initialize-venv: &initialize-venv
    name: Initialize Virtual Environment
    command: |
      python -m virtualenv ../venv || python -m venv ../venv
      . ../venv/bin/activate

  ci-steps: &ci-steps
    steps:
      - checkout
      - run:
          <<: *initialize-venv
      - run:
          name: Install "PyPI upload" distribution dependencies
          command: |
            . ../venv/bin/activate
            python -m pip install --disable-pip-version-check --upgrade pip
            pip install -U setuptools twine wheel
      - run:
          name: Build "PyPI upload" distribution
          command: |
            #
            # Set UPLOAD_SDIST environment variable
            #
            export UPLOAD_SDIST=$(echo ${CIRCLE_JOB} | cut -d"_" -f2)
            echo "UPLOAD_SDIST [${UPLOAD_SDIST}]"
            #
            # Run CI
            #
            . ../venv/bin/activate
            python setup.py sdist bdist_wheel
            #
            # if it applies, remove source distribution
            #
            if [[ $UPLOAD_SDIST == "" ]]
            then
              echo "Deleting source distribution"
              rm -f dist/*.tar.gz
            fi
      - run:
          name: install ctest_junit_formatter prerequisites
          command: |
            . ../venv/bin/activate
            git clone git://github.com/scikit-build/scikit-ci-addons -b master
            pip install -r ./scikit-ci-addons/requirements.txt
            pip install ./scikit-ci-addons
      - run:
          name: ctest_junit_formatter
          command: |
            . ../venv/bin/activate
            mkdir -p ~/ctest-reports
            (cd case0; ci_addons ctest_junit_formatter $(pwd) > ~/ctest-reports/JUnit-${CIRCLE_NODE_INDEX}.xml)
            (cd case1; ci_addons ctest_junit_formatter $(pwd) > ~/ctest-reports/JUnit-1.xml)
      - store_test_results:
          path: ~/ctest-reports
      - persist_to_workspace:
          root: ./
          paths:
            - dist

  no_filters: &no_filters
    filters:
      tags:
        only: /.*/

version: 2
jobs:
  python27:
    docker:
      - image: circleci/python:2.7.15-jessie
    <<: *ci-steps
  python35:
    docker:
      - image: circleci/python:3.5.5-jessie
    <<: *ci-steps
  python36:
    docker:
      - image: circleci/python:3.6.6-jessie
    <<: *ci-steps
  python37_upload-sdist:
    docker:
      - image: circleci/python:3.7.0-stretch
    <<: *ci-steps

  deploy-master:
    docker:
      - image: circleci/python:3.7.0-stretch
    steps:
    - attach_workspace:
        at: ./
    - run:
        name: Deploy master
        command: |
          echo "Deploy master"
          ls dist
  deploy-release:
    docker:
      - image: circleci/python:3.7.0-stretch
    steps:
    - attach_workspace:
        at: ./
    - run:
        name: Deploy release
        command: |
          echo "Deploy release"
          python -m venv ../venv
          . ../venv/bin/activate
          pip install twine
          ls dist
          twine upload -u $PYPI_USER -p $PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ dist/*

workflows:
  version: 2
  test-package-publish:
    jobs:
      - python27:
          <<: *no_filters
      - python35:
          <<: *no_filters
      - python36:
          <<: *no_filters
      - python37_upload-sdist:
          <<: *no_filters
      - deploy-release:
          requires:
            - python27
            - python35
            - python36
            - python37_upload-sdist
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deploy-master:
          requires:
            - python27
            - python35
            - python36
            - python37_upload-sdist
          filters:
            branches:
              only: master

