version: 2

references:

  ci_steps: &ci_steps
    working_directory: /work
    steps:
      - checkout
      - run:
          name: Run CI
          command: |
            export MANYLINUX_PYTHON=$(echo ${CIRCLE_JOB} | cut -d"_" -f2)
            echo "MANYLINUX_PYTHON [${MANYLINUX_PYTHON}]"
            /opt/python/${MANYLINUX_PYTHON}/bin/pip install scikit-ci
            /opt/python/${MANYLINUX_PYTHON}/bin/ci
      - run:
          name: install "ctest_junit_formatter" prerequisites
          command: |
            export MANYLINUX_PYTHON=$(echo ${CIRCLE_JOB} | cut -d"_" -f2)
            echo "MANYLINUX_PYTHON [${MANYLINUX_PYTHON}]"
            #
            export PATH=/opt/python/${MANYLINUX_PYTHON}/bin:${PATH}
            git clone git://github.com/scikit-build/scikit-ci-addons -b master
            pip install -r ./scikit-ci-addons/requirements.txt
            pip install ./scikit-ci-addons
      - run:
          name: run "ctest_junit_formatter"
          command: |
            export MANYLINUX_PYTHON=$(echo ${CIRCLE_JOB} | cut -d"_" -f2)
            echo "MANYLINUX_PYTHON [${MANYLINUX_PYTHON}]"
            #
            export PATH=/opt/python/${MANYLINUX_PYTHON}/bin:${PATH}
            mkdir -p ~/ctest-reports
            (cd case0; ci_addons ctest_junit_formatter $(pwd) > ~/ctest-reports/JUnit-${CIRCLE_NODE_INDEX}.xml)
            (cd case1; ci_addons ctest_junit_formatter $(pwd) > ~/ctest-reports/JUnit-1.xml)
      - store_test_results:
          path: ~/ctest-reports

      - persist_to_workspace:
          root: ./
          paths:
            - dist

  x64_build_job: &x64_build_job
    docker:
      - image: dockcross/manylinux2014-x64
    <<: *ci_steps

  build_job_filters: &build_job_filters
    filters:
      tags:
        ignore:
          - latest
          - latest-tmp

jobs:

  # x64
  manylinux-x64_cp27-cp27m:
    <<: *x64_build_job
  manylinux-x64_cp27-cp27mu:
    <<: *x64_build_job
  manylinux-x64_cp37-cp37m_upload-sdist:
    <<: *x64_build_job

  # x86
  # NA

  deploy-master:
    docker:
      - image: circleci/python:3.9.4-buster
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy master
          command: |
            echo "Deploy master (not implemented)"

  deploy-release:
    docker:
      - image: circleci/python:3.9.4-buster
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy release
          command: |
            echo "Deploy release"
            python -m venv ../venv
            . ../venv/bin/activate
            pip install twine
            ls dist
            twine upload -u $PYPI_USER -p $PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*

workflows:
  version: 2
  build-test-deploy:
    jobs:
      # x64
      - manylinux-x64_cp27-cp27m:
          <<: *build_job_filters
      - manylinux-x64_cp27-cp27mu:
          <<: *build_job_filters
      - manylinux-x64_cp37-cp37m_upload-sdist:
          <<: *build_job_filters
      # x86
      # NA

      - deploy-master:
          requires:
            # x64
            - manylinux-x64_cp27-cp27m
            - manylinux-x64_cp27-cp27mu
            - manylinux-x64_cp37-cp37m_upload-sdist
            # x86
            # NA
          filters:
            branches:
              only: master
      - deploy-release:
          requires:
            # x64
            - manylinux-x64_cp27-cp27m
            - manylinux-x64_cp27-cp27mu
            - manylinux-x64_cp37-cp37m_upload-sdist
            # x86
            # NA
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/
            branches:
              ignore: /.*/
