name: Slicer CI

on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Build Slicer'
        uses: ./.github/actions/slicer-build
