name: Slicer CI

on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - "main-ci"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "main-ci"
    paths-ignore:
      - "**.md"
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-slicer:
    name: Build Slicer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Slicer Build'
        id: slicer-build
        uses: ./.github/actions/slicer-build

      - name: 'Upload Slicer package'
        run: |
          echo "RUNNER_TEMP: ${{ runner.temp }}"
          echo "RUNNER_TEMP: ${{ env.RUNNER_TEMP }}"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          echo "package: ${{ steps.slicer-build.outputs.package }}"
          echo "${{ github.workspace }}/${{ steps.slicer-build.outputs.package }}"


      - name: 'Upload Slicer package'
        uses: actions/upload-artifact@v2
        with:
          name: slicer-package
          path: ${{ github.workspace }}/${{ steps.slicer-build.outputs.package }}
          retention-days: 1
