name: Update Slicer.crt certificate bundle

on:
  schedule:
    - cron: "30 11 * * 2"
  workflow_dispatch:

jobs:
  update-slicer-certificate-bundle:
    name: Update Slicer.crt certificate bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download certdata.txt from https://github.com/mozilla/gecko-dev
        run: |
          cd Base/QTCore/Resources/Certs                           &&
          certhost='https://github.com/mozilla/gecko-dev'          &&
          certdir='/blob/master/security/nss/lib/ckfw/builtins'    &&
          url="$certhost$certdir/certdata.txt?raw=true"            &&
          curl -L# -o certdata.txt $url

      - name: Generate Slicer.crt
        run: |
          cd Base/QTCore/Resources/Certs                           &&
          ./make-ca.sh

      - name: Cleanup
        run: |
          cd Base/QTCore/Resources/Certs                           &&
          rm certdata.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CI_SANDBOX_CREATE_PULL_REQUEST_GITHUB_TOKEN }}
          commit-message: "ENH: Update Slicer.crt CA bundle"
          committer: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
          author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
          signoff: false
          branch: slicerbot/update-slicer-certificate-bundle
          delete-branch: true
          title: "Update Slicer.crt CA bundle"
          body: ""
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

